#include "Erelia.h"

struct Stat_data
{
    int PA;
    int PM;
    int HP;
    int attack;
    int defense;
    int attack_spe;
    int defense_spe;
    int initiative;
};

void generate_creature_data()
{
    jgl::Array<jgl::String> name = {
    "Bulbizarre",
    "Herbizarre",
    "Florizarre",
    "Salameche",
    "Reptincel",
    "Dracaufeu",
    "Carapuce",
    "Carabaffe",
    "Tortank",
    "Chenipan",
    "Chrysacier",
    "Papilusion",
    "Aspicot",
    "Coconfort",
    "Dardargnan",
    "Roucool",
    "Roucoups",
    "Roucarnage",
    "Rattata",
    "Rattatac",
    "Piafabec",
    "Rapasdepic",
    "Abo",
    "Arbok",
    "Pikachu",
    "Raichu",
    "Sabelette",
    "Sablaireau",
    "Nidoran F",
    "Nidorina",
    "Nidoqueen",
    "Nidoran M",
    "Nidorino",
    "Nidoking",
    "Melofee",
    "Melodelfe",
    "Goupix",
    "Feunard",
    "Rondoudou",
    "Grodoudou",
    "Nosferapti",
    "Nosferalto",
    "Mystherbe",
    "Ortide",
    "Rafflesia",
    "Paras",
    "Parasect",
    "Mimitoss",
    "Aeromite",
    "Taupiqueur",
    "Triopikeur",
    "Miaouss",
    "Persian",
    "Psykokwak",
    "Akwakwak",
    "Ferosinge",
    "Colossinge",
    "Caninos",
    "Arcanin",
    "Ptitard",
    "Têtarte",
    "Tartard",
    "Abra",
    "Kadabra",
    "Alakazam",
    "Machoc",
    "Machopeur",
    "Mackogneur",
    "Chetiflor",
    "Boustiflor",
    "Empiflor",
    "Tentacool",
    "Tentacruel",
    "Racaillou",
    "Gravalanch",
    "Grolem",
    "Ponyta",
    "Galopa",
    "Ramoloss",
    "Flagadoss",
    "Magneti",
    "Magneton",
    "Canarticho",
    "Doduo",
    "Dodrio",
    "Otaria",
    "Lamantine",
    "Tadmorv",
    "Grotadmorv",
    "Kokiyas",
    "Crustabri",
    "Fantominus",
    "Spectrum",
    "Ectoplasma",
    "Onix",
    "Soporifik",
    "Hypnomade",
    "Krabby",
    "Krabboss",
    "Voltorbe",
    "Electrode",
    "Nœunœuf",
    "Noadkoko",
    "Osselait",
    "Ossatueur",
    "Kicklee",
    "Tygnon",
    "Excelangue",
    "Smogo",
    "Smogogo",
    "Rhinocorne",
    "Rhinoferos",
    "Leveinard",
    "Saquedeneu",
    "Kangourex",
    "Hypotrempe",
    "Hypocean",
    "Poissirene",
    "Poissoroy",
    "Stari",
    "Staross",
    "M. Mime",
    "Insecateur",
    "Lippoutou",
    "Elektek",
    "Magmar",
    "Scarabrute",
    "Tauros",
    "Magicarpe",
    "Leviator",
    "Lokhlass",
    "Metamorph",
    "Evoli",
    "Aquali",
    "Voltali",
    "Pyroli",
    "Porygon",
    "Amonita",
    "Amonistar",
    "Kabuto",
    "Kabutops",
    "Ptera",
    "Ronflex",
    "Artikodin",
    "Electhor",
    "Sulfura",
    "Minidraco",
    "Draco",
    "Dracolosse",
    "Mewtwo",
    "Mew",
    };
    jgl::Array<int> index = {
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,//10
        3,
        3,
        3,
        3,
        3,
        1,
        1,
        1,
        3,
        3,//20
        1,
        1,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,//30
        3,
        3,
        3,
        3,
        2,
        2,
        3,
        3,
        2,
        2,//40
        1,
        1,
        3,
        3,
        3,
        3,
        3,
        3,
        1,
        3,//50
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,//60
        4,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,//70
        3,
        4,
        4,
        3,
        3,
        3,
        3,
        3,
        3,
        3,//80
        3,
        3,
        1,
        1,
        1,
        4,
        4,
        3,
        3,
        4,//90
        4,
        3,
        3,
        3,
        3,
        3,
        3,
        4,
        4,
        3,//100
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        2,
        3,
        3,//110
        3,
        3,
        2,
        3,
        3,
        4,
        4,
        4,
        4,
        4,//120
        4,
        2,
        3,
        2,
        3,
        3,
        3,
        3,
        4,
        4,//130
        4,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,//140
        3,
        1,
        3,
        1,
        1,
        1,
        3,
        3,
        3,
        3,//150
        2
    };
    jgl::Array<jgl::Vector2> sprite = {
        jgl::Vector2(0, 36),//oiseau
        jgl::Vector2(0, 37),//melofee
        jgl::Vector2(0, 38),//kangourex
        jgl::Vector2(0, 39),//poison
    };

    jgl::Array< Stat_data> stat_array = {
        {6, 3, 20}
    };


    for (size_t i = 0; i < name.size(); i++)
    {
        jgl::String file_name = jgl::normalize_string(jgl::itoa(i), '0', 3) + "-" + name[i];
        std::fstream file = jgl::open_file("ressources/creature/" + file_name + ".crea", std::ios_base::out | std::ios_base::trunc);
        file << i + 1 << std::endl;
        file << name[i] << std::endl;
        file << i % 16 << ";" << i / 16 << std::endl;
        file << jgl::itoa(sprite[index[i] - 1].x) << ";" << jgl::itoa(sprite[index[i] - 1].y) << std::endl;
        file << 6 << std::endl;
        file << 3 << std::endl;
    }
}
